### ISSUE TITLE
Controller 'ngModel', required by directive 'toggleSwitch', can't be found!

### ISSUE THREAD

**Issue by curtiskelsey** [zfcampus/zf-apigility-admin-ui#101]
Found in version 1.2.2, When adding options to a Zend\I18n\Validator\Alnum validator, toggleSwitch does not load. Occurs in Zend\I18n\Validator\Alpha as well. It may be broken across all validator options. I have not confirmed this, however.

**Comment by spectravp** [comment]
+1  Same here

**Comment by spectravp** [comment]
Hope they fix this soon. It makes it nearly unusable.

**Comment by hoebbelsB** [comment]
+1

**Comment by Zbintiosul** [comment]
+1

**Comment by spectravp** [comment]
Ugh... this is a duplicate of this issue from Oct 2015, https://github.com/zfcampus/zf-apigility-admin-ui/issues/90

**Comment by saulotoledo** [comment]
This was fixed in 1.2.4. https://github.com/zfcampus/zf-apigility-admin-ui/issues/90 is also closed.
I could not replicate the issue. @michalbundyra, I believe this can be closed.

**Comment by michalbundyra** [comment]
Thanks, @saulotoledo!
