### ISSUE TITLE
Standard Filters missing

### ISSUE THREAD

**Issue by spectravp** [zfcampus/zf-apigility-admin-ui#102]
Zend's standard filters are now absent from the filters list. This is from a download of the 1.3.2 archive and straight up vagrant up.

**Comment by spectravp** [comment]
Looks like it is ignoring the filter_metadata array key and instead looking for the filters->invokables key. If I add a list of Zend Filter names there, they appear.

**Comment by spectravp** [comment]
These are the only 2 filters available in v 1.3.3
<img width="628" alt="screen shot 2016-03-17 at 4 23 36 pm" src="https://cloud.githubusercontent.com/assets/272688/13860007/ace7668e-ec5c-11e5-9dc0-5a79fe9b22d6.png">

**Comment by Lansoweb** [comment]
Hi @spectravp. Actually it's not a problem in the UI, but in the admin module as in https://github.com/zfcampus/zf-apigility-admin/issues/337.

**Comment by weierophinney** [comment]
I believe this is resolved now; please update to the latest admin and/or admin-ui releases, and verify. Re-open the issue if you are still observing a problem, and provide the following details:

- Results of executing `composer show`
- A screenshot like you did before, demonstrating what you observe in the select box.

Thanks!
