### ISSUE TITLE
Unable to fetch validator list

### ISSUE THREAD

**Issue by spectravp** [zfcampus/zf-apigility-admin-ui#105]
Apigility API responds with a status 406. Unable to fetch validator list. Clean download of packaged version 1.3.3.   Can't really use validators any way due to this error since October: https://github.com/zfcampus/zf-apigility-admin-ui/issues/90

**Comment by spectravp** [comment]
Closing. Believe this was related to Vagrant/Apache config and not Apigility

**Comment by intellent** [comment]
@spectravp Having the same issue. Could you please elaborate, what exactly you changed in your Apache config?
