### ISSUE TITLE
Admin url not working and link not showing

### ISSUE THREAD

**Issue by Michal-sk** [zfcampus/zf-apigility-admin-ui#129]
So i am having a issue with getting the admin ui working.

I enabled development mode and development.config.php is loaded and contains:

``` php
<?php
return [
    'modules' => [
        'ZF\\Apigility\\Admin\\Ui',
    ],
];
```

But nothing shows and the admin path does not work. So after doing some reading im unsure what documentation to follow.
- https://apigility.org/documentation/modules/zf-apigility-admin talks about the module Admin and not Admin\Ui
- https://github.com/zfcampus/zf-apigility-admin-ui talks about Admin\Ui but nothing shows...

``` json

    "require": {
        "php": "^5.5 || ^7.0",
        "zfcampus/zf-apigility": "^1.3",
        "zfcampus/zf-apigility-documentation": "^1.2",
        "woonon/core": "dev-master",
        "zfcampus/zf-oauth2": "^1.4",
        "zendframework/zend-cache": "^2.7",
        "zendframework/zend-mvc-i18n": "^1.0",
        "zendframework/zend-log": "^2.9"
    },
    "require-dev": {
        "zfcampus/zf-apigility-admin": "^1.5",
        "zfcampus/zf-apigility-admin-ui": "^1.3",
        "zfcampus/zf-deploy": "~1.0",
        "zfcampus/zf-asset-manager": "^1.0",
        "zfcampus/zf-development-mode": "^3.0",
        "zendframework/zend-developer-tools": "^1.1"
    }
```

**Comment by colinkelly** [comment]
This is not an issue with the repo but rather an issue with your configuration of LAMP(or LEMP these dayz).

Please verify your error logs in order to investigate. Let us know if you find anything relevant to this project.

**Comment by Michal-sk** [comment]
Right so it turns out this is not perse a admin-ui issue, rather a documentation issue.

In the development config modules we not only add `ZF\\Apigility\\Admin\\Ui` but we also MUST add `ZF\\Apigility\\Admin`. This is nowhere mentioned in the docs.
