### ISSUE TITLE
[solved] Unable to fetch RPC services

### ISSUE THREAD

**Issue by guidofaecke** [zfcampus/zf-apigility-admin-ui#132]
After switching back and forth with
`./vendor/bin/zf-development-mode disable`
and 
`./vendor/bin/zf-development-mode enable`
Apigility is now showing only the icon, but no service names. It also greets me with "Unable to fetch RPC services"

**Comment by jguittard** [comment]
Any errors in the console while fetching those services?

**Comment by guidofaecke** [comment]
Nothing at all

**Comment by guidofaecke** [comment]
Never mind... after checking the Network Tab in the Chrome Developer Tools I saw the problem. One of my factories was not correctly defined.
