### ISSUE TITLE
Documentation link throws 404 Not found - ZF3

### ISSUE THREAD

**Issue by divix1988** [zfcampus/zf-apigility-admin-ui#135]
When clicking on Documentation link on top of the UI, the API throws 404 not found error message:

**Request:**
http://localhost/zend3/apigility/documentation

**Response:**
`{"type":"http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html","title":"Not Found","status":404,"detail":"Page not found."}`

(I might be missing some Zend component dependencies, but I am unsure which, as apigility doesn't require any).

**Comment by webimpress** [comment]
Do you have installed and enabled module [`zfcampus/zf-apigility-documentation`](https://github.com/zfcampus/zf-apigility-documentation)?

**Comment by divix1988** [comment]
That worked thanks, are there any more required dependences?

**Comment by webimpress** [comment]
Please check [`composer.json` of `zend-apigility-skeleton`](https://github.com/zfcampus/zf-apigility-skeleton/blob/master/composer.json#L28-L34) application.

**Comment by divix1988** [comment]
Cheers.
