### ISSUE TITLE
error notice:Unable to fetch documentation

### ISSUE THREAD

**Issue by solody** [zfcampus/zf-apigility-admin-ui#143]
i'm using Apigility 1.4.1

When a module name including namespace slash,  like "MyVendor/MyModule"，the api documentation's url is `/apigility/documentation/MyVendor.MyModule-v1`, but `zf-apigility-admin-ui` generate the url as `/apigility/documentation/MyVendor%5CMyModule-v1`，so it get a `404 not found` response, then this error occurred.

this problem occurred in `zf-apigility-documentation-swagger` too.

someone count fix this ?

**Comment by saulotoledo** [comment]
@michalbundyra, could you confirm this is the expected behavior?

**Comment by michalbundyra** [comment]
@saulotoledo I believe it is a bug and namespace separator should be changed to `.` in that case.
Not sure if it was tested with "nested" modules, but if the correct link to the documentation is with `.` I believe admin-ui should use the same.

**Comment by saulotoledo** [comment]
I could not replicate the issue. Swagger page also contains links with `.` already. That may be already fixed before, or I did not understand the problem. There are indeed a few cases in the URL with `%5C`, but they are not leading to `404 not found` and we may not need to change them.

@solody could you confirm this is still an issue? If yes, could you provide more details? @michalbundyra, if you replicate this issue, could you provide some more information?

If this is not an issue anymore we can close it.

**Comment by michalbundyra** [comment]
@saulotoledo tested on my instance and also I cannot replicate the issue. Thanks!
