### ISSUE TITLE
Angular 2 + ZF3

### ISSUE THREAD

**Issue by taat** [zfcampus/zf-apigility-admin-ui#144]
I'm looking for any reference project using Angular (not AngularJS) and ZF2 or ZF3 together. I was hoping that this repo could be such a project, but I see AngularJS, which is a lot different than Angular2.
Does anyone use Angular and ZF3 together yet (with Bootstrap, without jQuery)?
Any plans on moving to Angular2?

**Comment by saulotoledo** [comment]
@michalbundyra It has been a long time since the author comment and it is off-topic. I suggest to close it.

**Comment by michalbundyra** [comment]
Please use [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/) to ask a questions in future. Thanks!
