### ISSUE TITLE
Unable to fetch content-negotiation details

### ISSUE THREAD

**Issue by bigred38** [zfcampus/zf-apigility-admin-ui#145]
Hello,
I installed apigiility from scratch and after I followed this to include apigility into my project.

But When I run the apigility admin page, I got error like : 
Unable to fetch content-negotiation details

With my console : 
1bc54cd5.vendor.js:4 GET http://kit_2.0_php7/apigility/api/content-negotiation 404 (Not Found)

**Comment by bigred38** [comment]
I found the solution

**Comment by webimpress** [comment]
@bigred38 can you share your solution, please? It will be good to have it for reference. If it is no logner an issue, please close it.

**Comment by saulotoledo** [comment]
@michalbundyra I also suggest to close this one. It has been a long time since the author comment and cannot be reproduced.

**Comment by michalbundyra** [comment]
Thanks, @saulotoledo!

**Comment by saulotoledo** [comment]
@michalbundyra I also suggest to close this one. It has been a long time since the author comment and cannot be reproduced.

**Comment by saulotoledo** [comment]
Ops, I deleted and recreated the comment by accident :-S
But ok, it is closed now.
