### ISSUE TITLE
Documentation not saving for entity docs

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#19]
The payload for collections shows collection -> GET, POST, etc.

However the payload when saving entities has numbers instead of HTTP verbs. This causes the validator on saving docs to reject the payload. It's not currently possible to save docs via the UI for entities.

![image](https://cloud.githubusercontent.com/assets/775393/6924093/3f860228-d793-11e4-9b14-8669fca3d7b1.png)

**Comment by ezimuel** [comment]
@dstockto I just send the PR #22 to fix this issue and other minor fixes.

**Comment by weierophinney** [comment]
Fixed with #22

**Comment by dstockto** [comment]
Confirmed working. Thank you.
