### ISSUE TITLE
New UI - DB Adapter setup masks fields it shouldn't

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#20]
In the new UI when configuring a new Db Adapter, the UI masks fields that should probably not be masked. These are hostname, port and charset.

![image](https://cloud.githubusercontent.com/assets/775393/6924140/97332118-d793-11e4-8993-5754295b373f.png)

**Comment by ezimuel** [comment]
@dstockto this issue has been fixed in PR #15.

**Comment by dstockto** [comment]
Confirmed working. Thank you.
