### ISSUE TITLE
Creating service that already exists changes config file

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#23]
If you attempt to create a service on a resource and that resource already exists, the config is written (or at least part of it). On mine the parts it definitely changed were:

* The route 
* Added another identical line to zf-versioning -> uri

Additionally an unrelated service that had been manually added 'haystack' added for a validator  was rewritten with numerical array indices. I'm assuming this would've happened anyway based on how configs are written.

The API / admin ui does report that the API already exists, but the config changes are made anyway.

![image](https://cloud.githubusercontent.com/assets/775393/7016415/fa32b816-dca0-11e4-96e6-d2e39a781640.png)

**Comment by weierophinney** [comment]
@dstockto Is this under 1.0 or the develop branch?

@ezimuel Can you look into this?

**Comment by dstockto** [comment]
@weierophinney dev-develop

I'm not sure if this should be a ticket in the API rather than the UI.

**Comment by ezimuel** [comment]
@dstockto I just checked with master branch and it seems the only issue is related with ['zf-versioning']['uri'] with the addition of another version. In the route I don't see any error. Can you confirm?
It's definitely an issue of https://github.com/zfcampus/zf-apigility-admin.

Regarding the rewrite of existing values with numerical array index I guess we cannot do nothing, this comes from the usage of https://github.com/zfcampus/zf-configuration that works in that way.

**Comment by ezimuel** [comment]
I just sent 2 PRs to fix this issue:
- https://github.com/zfcampus/zf-apigility-admin/pull/297
- https://github.com/zfcampus/zf-apigility-admin-ui/pull/65
