### ISSUE TITLE
Display problem when adding new collection query whitelist terms with "Enter"

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#24]
In the new admin-ui, from a fresh page load (hard reload, go to API resource) I put in a new collection whitelist term, typing 

account_id<enter>

This turned it into the blue pill with account_id, but when I clicked the save button, it changed to an empty pill:

![image](https://cloud.githubusercontent.com/assets/775393/7073582/ac1e8368-deb1-11e4-852c-26c65a6820e2.png)

It doesn't appear to do this if I make the term into a pill by pressing the spacebar. Reloading the UI will show that the correct term did make it into the config.

**Comment by dstockto** [comment]
Upon further investigation, it appears to happen any time I hit the save button, regardless of how the value was created (space or enter) and regardless of whether anything was actually changed.

**Comment by toringe** [comment]
Can confirm this in the latest 1.1.4. Strings are added correctly when I use `spacebar` or `tab` and if I add two or more strings, then the `save` button works. But for all other cases, the first element becomes empty.

**Comment by ezimuel** [comment]
The PR #62 solve this issue. @weierophinney can you review? Thanks.

**Comment by ezimuel** [comment]
Thr PR #62 has been merged.
