### ISSUE TITLE
Displaying an RPC service after it's been created causes failures

### ISSUE THREAD

**Issue by jguittard** [zfcampus/zf-apigility-admin-ui#27]
_Up to date with develop branches from zf-apigility-admin, zf-apigility-admin-ui, zf-rest and zf-mvc-auth._

To reproduce : create an RPC service, with whatever name or route
- Landing page show details screen which is empty (same goes when fetching from the service list in the sidebar)
- When trying to delete the service, landing page is empty too.

Root causes:
- Upon fetching, a while loop in Angular causes an error (trying to iterate through _embedded.input_filter, which is not defined

![capture d ecran 2015-04-14 a 18 12 24](https://cloud.githubusercontent.com/assets/5320213/7141446/f2ce4252-e2d1-11e4-9a4d-7617e27bf21b.png)

- Upon deletion, an exception is raised on the server side (Model/RpcServiceResource)

![capture d ecran 2015-04-14 a 18 13 00](https://cloud.githubusercontent.com/assets/5320213/7141451/f978b59c-e2d1-11e4-8d13-d9b798ce1c6e.png)

**Comment by weierophinney** [comment]
I cannot reproduce this with the current develop branch of the admin or UI.

**Comment by weierophinney** [comment]
Deletion worked as expected, too.

**Comment by jguittard** [comment]
I'll start from a blank project and set admin, admin-UI and rest to develop branches

**Comment by jguittard** [comment]
So, I finally got the scenario. From a blank default project, update the composer with develop branches for zf-mvc-auth, zf-rest, zf-apigility-admin and zf-apigility-admin-ui, and update composer.
Then create an RPC service, details show up. Added info on its documentation tab and save. Refresh the page, the details are blank.
Then if you try to delete the service, the landing page receive a 400 response (version missing for the request)

**Comment by weierophinney** [comment]
Okay, confirmed that the details disappear on a refresh. From what I can see, the API call is properly being made, but I'm seeing some angular errors pop up, which tells me we likely have a problem with how it deals with the returned payload.

When I delete, the delete operation itself is successful, but the problem is the missing "version" when sending the request; this should be a default value.

**Comment by weierophinney** [comment]
Okay, Fixes on both develop of this repo and the zf-apigility-admin repo fix these situations.
