### ISSUE TITLE
UI breaks in several ways with latest Firefox on Mac

### ISSUE THREAD

**Issue by jguittard** [zfcampus/zf-apigility-admin-ui#28]
See screenshots below

![capture d ecran 2015-04-15 a 15 02 32](https://cloud.githubusercontent.com/assets/5320213/7159205/cff6ed88-e380-11e4-8e2f-471041a4ea2e.png)
![capture d ecran 2015-04-15 a 15 02 51](https://cloud.githubusercontent.com/assets/5320213/7159208/d01c69e6-e380-11e4-82ad-5ae85a3186fe.png)
![capture d ecran 2015-04-15 a 15 03 05](https://cloud.githubusercontent.com/assets/5320213/7159207/d018c002-e380-11e4-8f52-2d8c01b47650.png)
![capture d ecran 2015-04-15 a 15 04 36](https://cloud.githubusercontent.com/assets/5320213/7159209/d01dad7e-e380-11e4-95ba-a8a9c1022f8a.png)

**Comment by ezimuel** [comment]
@jguittard I think I fixed these UI issues in the PR that I'm working on. I'll send it in a couple of hours.

**Comment by jguittard** [comment]
Awesome @ezimuel!
Did you get the dropdown for source code work on Chrome ?

**Comment by ezimuel** [comment]
@jguittard yes, I also solved the issue for the source code reported in PR #18.

**Comment by ezimuel** [comment]
Solved in #29
