### ISSUE TITLE
Dropdowns not selectable with mouse

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#42]
I updated to 1.1.1 (zfcampus/zf-apigility-admin 1.1.2 and zfcampus/zf-apigility-admin-ui 1.1.4 and the dropdowns in the UI appear to not work when the mouse is used to select an option. I think I can choose using the keyboard to type and hit enter to select but if the mouse is used to select something the keyboard doesn't work and the mouse doesn't appear to be able to actually make the selection and close the select box. It seems to be happening in every select box: content negotiation, filter and validator options, hydrator selection.

The only selection box that doesn't appear to be affected is the source code viewing one.

![image](https://cloud.githubusercontent.com/assets/775393/7264782/1c6b881a-e84d-11e4-993d-a8285a82b388.png)

In the screenshot above, I can move the mouse over any of the options and it highlights, but clicking does nothing. Clicking outside the drop down will close the drop down but the selection remains whatever it was when I opened it.

I can use the selectors with the keyboard (arrow keys and enter or typing the selection or both).

**Comment by ezimuel** [comment]
@dstockto I cannot reproduce this issue, it's working fine now. I tested with Chrome, Firefox and Safari.

**Comment by dstockto** [comment]
It does seem to be working correctly in the latest version. Thank you.
