### ISSUE TITLE
Wrong text on delete filter modal

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#49]
When deleting a filter from a field in the new admin ui, the confirmation modal asks if you want to delete the driver option. It should probably ask about deleting a filter.

![image](https://cloud.githubusercontent.com/assets/775393/7423871/d6b91bc2-ef57-11e4-986a-655d48a21d81.png)

![image](https://cloud.githubusercontent.com/assets/775393/7423876/ea040d7c-ef57-11e4-8f74-d7ad0b176323.png)

**Comment by ezimuel** [comment]
@dstockto I just sent this PR #64 that fixes the issue. Thanks for reporting!
