### ISSUE TITLE
Doctrine Adapter link does not show in Dashboard

### ISSUE THREAD

**Issue by canetech** [zfcampus/zf-apigility-admin-ui#5]
i installed zf-apigility-doctrine using the latest apigility skeleton and when i visit the url: http://localhost:8888/apigility/ui#/
this is the output, no doctrine adapter menu is available.

![screen shot 2014-11-17 at 4 53 41 pm](https://cloud.githubusercontent.com/assets/9798326/5067207/57be5732-6e7a-11e4-9599-521bb0b91c22.png)

-----------
application.config.php

    'modules' => array(
        'Application',
        'ZF\DevelopmentMode',
        'ZF\Apigility',
        'ZF\Apigility\Provider',
        'ZF\Apigility\Documentation',
        'AssetManager',
        'ZF\ApiProblem',
        'ZF\Configuration',
        'ZF\MvcAuth',
        'ZF\OAuth2',
        'ZF\Hal',
        'ZF\ContentNegotiation',
        'ZF\ContentValidation',
        'ZF\Rest',
        'ZF\Rpc',
        'ZF\Versioning',
        'Phpro\DoctrineHydrationModule',
        'ZF\Apigility\Doctrine\Server',
    ),

------------
development.config.php

    'modules' => array(
        'ZFTool',
        'ZF\Apigility\Admin',
        'ZF\Apigility\Welcome',
        'ZF\Apigility\Doctrine\Admin',
    ),

------------

composer.json

    "require": {
        "php": ">=5.3.23",
        "zendframework/zendframework": ">=2.3.2,<3.0.0",
        "zfcampus/zf-apigility": "~1.0",
        "zfcampus/zf-apigility-documentation": "~1.0",
        "zfcampus/zf-development-mode": "~2.0",
        "zfcampus/zf-apigility-doctrine": "dev-master"
    },
    "require-dev": {
        "zendframework/zftool": "dev-master",
        "zendframework/zend-developer-tools": "dev-master",
        "zfcampus/zf-apigility-admin": "~1.0",
        "zfcampus/zf-apigility-welcome": "~1.0",
        "zfcampus/zf-deploy": "~1.0"
    }

**Comment by ezimuel** [comment]
We are working on it in the new UI, see PR https://github.com/zfcampus/zf-apigility-admin-ui/pull/15
