### ISSUE TITLE
Doctrine Hydrator Strategies - Wrong field names

### ISSUE THREAD

**Issue by thomasvargiu** [zfcampus/zf-apigility-admin-ui#52]
When I open the modal to add a new hydrator strategy, entity fields are populated as 
```<column_name> => <field_name>```
This cause to save the follow configuration:

```php
return array(
    'doctrine-hydrator' => array(
        'UserAPI\\V1\\Rest\\User\\UserHydrator' => array(
            'strategies' => array(
                'insert_time' => 'Zend\\Stdlib\\Hydrator\\Strategy\\DateTimeFormatterStrategy',
            ),
    ),
);
```

but, in my case, the field is named ```insertTime```.

The problem is at this [line](https://github.com/zfcampus/zf-apigility-admin-ui/blob/f073affe7285232740abd5ef19ee4171111b901e/src/apigility-ui/rest/rest.controller.js#L139)

**Comment by ezimuel** [comment]
@jguittard can you look this issue? Thanks!

**Comment by jguittard** [comment]
@thomasvargiu The field name is retrieved from Doctrine Metadata API, not from your entity implementation.
Plus, strategies are bound to the hydrator. So you may either use ClassMethods hydrator, or if you use another hydrator, add a Zend\Stdlib\Hydrator\NamingStrategy\UnderscoreNamingStrategy to your hydrator.

That could be something like:

```php
use Zend\Stdlib\Hydrator\NamingStrategy\UnderscoreNamingStrategy;

...

public function __construct()
{
    parent::__construct();
    $this->addStrategy('insertTime', new UnderscoreNamingStrategy());
}
```

**Comment by thomasvargiu** [comment]
I'm sorry, maybe the issue was incomplete.
I know that field name is retrieved from Doctrine Metadata API, but I think from the wrong field.
The problem with my entity is that property is defined something like this:
```php
...
class Foo {
    /**
     * @var \DateTime
     * @ORM\Column(name="insert_time", type="datetime", nullable=false)
     */
    protected $insertTime;
}
```

where property name is ```insertTime``` and column name is ```insert_time```. The default hydrator strategy use the property name and not the column name, but the value you are retrieving from metadata to write configuration is the column name (if I am right).

**Comment by ezimuel** [comment]
@jguittard can you review the PR provided by @thomasvargiu? Thanks!
