### ISSUE TITLE
Hostname and Charset fields have type password

### ISSUE THREAD

**Issue by RalfEggert** [zfcampus/zf-apigility-admin-ui#56]
When editing a database adapter the fields for hostname and charset have the type "password". Therefore the input in these fields cannot be read.

**Comment by jguittard** [comment]
This issue has been fixed a while ago. What version are you using ? (have a look at composer.json)

**Comment by RalfEggert** [comment]
Well, I am using 1.1.4 of `ZF\Apigility\Admin\Ui` which is quite up-to-date, I guess.

**Comment by guliano** [comment]
I confirm that. Problem occurs on edit form. On create form is ok.

**Comment by ezimuel** [comment]
@RalfEggert, @guliano this is already fixed in master, see here:
https://github.com/zfcampus/zf-apigility-admin-ui/blob/master/src/apigility-ui/modal/edit-db.html#L33
https://github.com/zfcampus/zf-apigility-admin-ui/blob/master/src/apigility-ui/modal/edit-db.html#L41
/cc @jguittard

**Comment by RalfEggert** [comment]
@ezimuel Yep, but if you do a fresh clone of the Apigility skeleton and install it via composer, it still is not fixed:

```
$ git clone https://github.com/zfcampus/zf-apigility-skeleton.git
$ cd zf-apigility-skeleton/
$ composer install
```

**Comment by ezimuel** [comment]
@RalfEggert we need to rebuild the javascript production fiels (using `grunt clean && grunt build`). I'm working on other issue now, I'll update the master asap. Thanks!

**Comment by RalfEggert** [comment]
No problem. you're welcome
