### ISSUE TITLE
Authentication page doesn't show custom OAuth2 Storage adapters

### ISSUE THREAD

**Issue by akrabat** [zfcampus/zf-apigility-admin-ui#68]
I've implemented a custom OAuth2 storage adapter with the following config:

```php
    'zf-mvc-auth' => [
        'authentication' => [
            'adapters' => [
                'MyTest' => [
                    'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',
                    'storage' => [
                        'storage' => 'MyAuth\OAuth2Adapter',
                        'route' => '/oauth',
                    ],
                ],
            ],
        ],
    ],
```

In the admin, when I click on the Authentication menu item at the top, my adapter is not shown in the list and I see an error of "Error fetching authentication adapters" (http://i.19ft.com/4b7165b5.png)

The console shows: http://i.19ft.com/fd9d5eb3.png

The list of available authentication types on a service page is correct though (http://i.19ft.com/9c127126.png).

**Comment by ezimuel** [comment]
@akrabat the Authentication menu is designed to manage only HTTP Basic/Digest and OAuth2 types and not custom adapters. I need to check for the error that you reported. We should likely list the custom adapter in the list of the Authentication page, even if you cannot edit it.

**Comment by akrabat** [comment]
Yeah, clearly it shouldn't be edited or probably deleted. I'm fine with there being a separate list as it'd be nice to see a complete overview on this page. At a minimum, no error would be nice :)

**Comment by nuxwin** [comment]
@akrabat 

Why you don't just redefine the service to point on your own factory?

**Comment by akrabat** [comment]
@nuxwin That doesn't fix the issue for other authentication adapters, such as say an OAuth1 one.

**Comment by ezimuel** [comment]
@akrabat I provided the PR #77 and https://github.com/zfcampus/zf-apigility-admin/pull/311 that add the support of custom auth adapters in the UI. Let me know if this solve your issue, thanks!

**Comment by weierophinney** [comment]
@akrabat — to test, add Enrico's forks as vcs repos in your `composer.json`, and specify `dev-{branch name}@dev` for each of the admin and admin-ui dependencies.

I want to make sure the changes address your needs before merging! :)

**Comment by akrabat** [comment]
Tested. It works for me on this project. Thanks @ezimuel !
