### ISSUE TITLE
Build API with hostname route

### ISSUE THREAD

**Issue by CasperF** [zfcampus/zf-apigility-admin-ui#73]
I've added Apigility and Apigility Admin (+ UI) to my existing Zend Framework 2 project and so far this is a really, really great tool. Very useful and intuitive, a really good job to everyone who worked on it!

One thing that I thought wasn't implemented or I just didn't find, was the possibility to route my API calls through a hostname parent route, and then route the services through the child routes.

This would make it possible to create the API routes like:
http://api.domain.com/user
http://api.domain.com/account/2

So it doesn't conlict with other modules working on the normal application /user route (for the web front-end for example).

Having to put prepend every route with /api is a bother and not very efficient for maintenance.

**Comment by ezimuel** [comment]
@CasperF Apigility doesn't support the specification of a hostname for API routing. As you noticed, you can differentiate between web calls and API with a prefix like `/api` (I know that can be boring to add). Anyway, your proposal it's an interesting feature to support in the next release. Thanks for reporting!
