### ISSUE TITLE
File /dist/apigility-ui/aa474560.apigility.js missing

### ISSUE THREAD

**Issue by gartner** [zfcampus/zf-apigility-admin-ui#79]
In this commit: https://github.com/zfcampus/zf-apigility-admin-ui/commit/ceb432fccd63bb896afcb155faaf05693b620443

it seems you forgot to add the file /dist/apigility-ui/aa474560.apigility.js

This makes the current state of the admin-ui unusable.

**Comment by Michal-sk** [comment]
Same issue.

**Comment by ezimuel** [comment]
This has been fixed in the current master.
