### ISSUE TITLE
/ not allowed in content types

### ISSUE THREAD

**Issue by gartner** [zfcampus/zf-apigility-admin-ui#81]
When trying to add to the 'Accept whitelist' and 'Content-Type whitelist', the UI will not accept entries with a / in it.

This makes it quite hard to add proper content-types ..... 
(This is in v1.2.1)

**Comment by ezimuel** [comment]
@gartner I changed the regexp in `[a-zA-Z-]+/[a-zA-Z0-9*_+.-]+` to be more compliant with the [standard specification](http://www.w3.org/Protocols/rfc1341/4_Content-Type.html). I also fixed the same issue for RPC service. Thanks!
