### ISSUE TITLE
Missing ng-model in bootstrap-toggle-switch creation

### ISSUE THREAD

**Issue by ildanno** [zfcampus/zf-apigility-admin-ui#90]
The following error appears on showing the "add validator" modal:
`Error: [$compile:ctreq] Controller 'ngModel', required by directive 'toggleSwitch', can't be found!`

**Comment by gabrielsomoza** [comment]
I ran in to this as well :+1:

**Comment by mbn18** [comment]
@ildanno 
The patch does not work on my platform.
The ver of zfcampus/zf-apigility-admin-ui is 1.2.2

The php throw

`Warning: sort() expects parameter 1 to be array, null given in /srv/httpd/apigility/vendor/zfcampus/zf-apigility-admin/src/Model/AbstractPluginManagerModel.php on line 65`

**Comment by spectravp** [comment]
+1
