### ISSUE TITLE
Fix cursor when a link has not href attribute

### ISSUE THREAD

**Issue by theoziran** [zfcampus/zf-apigility-admin-ui#94]

**Comment by gabrielsomoza** [comment]
The cursor doesn't show a hand if the `href` attribute is missing, which seems correct to me. Is there a specific area in the Admin where this isn't the case?

**Comment by colinkelly** [comment]
Haha lol good one ;)

Try it in your chrome console, you'll see.

**Comment by gabrielsomoza** [comment]
That's what I did, and didn't see anything weird. Maybe a screenshot would help in this case.

(BTW I'm not a repo maintainer)

**Comment by colinkelly** [comment]
I think we should just close this ticket. Obviously there is no serious issue here. @theoziran hasn't left anything in the description. If there is really an issue, he will see my tag and respond ;)

If this is an issue in the sort that he scrolled on top of an href then the cursor does not turn back in an arrow, than, this means that his computer ran out of RAM or was on swap.

However, if there is an <a> dom without any href, than there is no reason why it would be clickable. I agree that, for an issue with the UI, a screenshot should be definitely mandatory to help resolve the issue.

**Comment by theoziran** [comment]
An <a> tag without href will show a text cursor by default. If you find in the project will see many of <a /> with just ng-click attribute.

![screen_1](https://cloud.githubusercontent.com/assets/331873/12856425/13f33368-cc2c-11e5-9b11-d9ff6aa70c06.PNG)
![screen_2](https://cloud.githubusercontent.com/assets/331873/12856426/13f7e818-cc2c-11e5-80ab-dbe11b821e77.PNG)

**Comment by colinkelly** [comment]
Oh I see the issue.  This is more because angular does not correct it in there css. We can add it to the [dashboard.css](https://github.com/colinkelly/zf-apigility-admin-ui/commit/529fcff3a8b6260b4b707f6f175ddea79e573f11) file as the following:

[ng-click],
[data-ng-click],
[x-ng-click] {
    cursor: pointer;
}

Or, it can be done in an other fashion just as such:

a {
 cursor: pointer;
}


;)

**Comment by colinkelly** [comment]
A pull request has been added for this issue: #100   ;)

**Comment by weierophinney** [comment]
Closed with #100.
